### ISSUE TITLE
00-yml配置

### ISSUE THREAD

**Issue by likunpeng0127** [likunpeng0127/market#2]
#### mybatis 
- 自动给实体类取别名 方便xml调用
- mybatis执行sql打印日志到控制台
- 开启驼峰命名
- xml文件加载路径
#### 分页插件
- 合理配置  自动修改  比如共100页数据要查 101页就会自动修改为100页
```yml
# 配置mybatis
mybatis:
  type-aliases-package: com.itheima.stock.pojo.entity    # 批量给实体类取别名。让xml中能够直接使用别名
  mapper-locations: classpath:com/itheima/stock/pojo/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 把mybatis执行的sql直接输出到终端中
# pagehelper配置
pagehelper:
  helper-dialect: mysql #指定分页数据库类型（方言）
  reasonable: true #合理查询超过最大页，则查询最后一页   比如最多数据
```
